// @vitest-environment node
//
// Slot-collision invariant for editor schemas.
//
// A groupKey declares a sibling set: tokens that share a groupKey are linked
// peers (`getComponentPropertySiblings`, `isComponentPropertyLinked`,
// `setComponentAliasLinked`). The codebase convention (src/styles/CONVENTIONS.md)
// requires shared groupKeys to cross only a VARIANT axis — never a slot/part
// axis. Crossing slots produces "phantom siblings": the schema reports header
// and cell as linked peers, but the linked block can't surface them because
// the editor's `linkableContexts` (correctly) treats them as independent.
//
// `registerComponentSchema` already warns at runtime when a typography
// groupKey covers multiple slots (e.g. one groupKey holding both
// `--card-...-title-font-family` and `--card-...-body-font-family`). This
// test asserts the invariant instead of relying on a console warning that
// nothing fails on.
//
// Caught the TableEditor regression where `header` and `cell` typography
// shared `family`/`size`/`weight`/`height` groupKeys (and `surface`/`padding`
// shared groupKeys across header/stripe and header/cell respectively). See
// the commit that introduced this test for context.

import { describe, it, expect } from 'vitest';
import { getComponentRegistryEntries } from './registry';

const TYPOGRAPHY_PROP_SUFFIXES = ['font-family', 'font-size', 'font-weight', 'line-height'] as const;

/** Mirror of `typographySlotOf` in `lib/slices/components.ts`. */
function typographySlotOf(varName: string): string | null {
  for (const suffix of TYPOGRAPHY_PROP_SUFFIXES) {
    if (!varName.endsWith('-' + suffix)) continue;
    const head = varName.slice(0, -(suffix.length + 1));
    const lastDash = head.lastIndexOf('-');
    if (lastDash < 0) return null;
    return head.slice(lastDash + 1);
  }
  return null;
}

describe('editor groupKey slot invariant', () => {
  for (const entry of getComponentRegistryEntries()) {
    it(`${entry.id}: no typography groupKey straddles multiple slots`, () => {
      const byKey = new Map<string, string[]>();
      for (const t of entry.schema as Array<{ variable: string; groupKey?: string }>) {
        if (!t.groupKey) continue;
        const list = byKey.get(t.groupKey) ?? [];
        list.push(t.variable);
        byKey.set(t.groupKey, list);
      }
      const violations: string[] = [];
      for (const [gk, vars] of byKey) {
        const slots = new Set<string>();
        for (const v of vars) {
          const slot = typographySlotOf(v);
          if (slot) slots.add(slot);
        }
        if (slots.size > 1) {
          violations.push(
            `groupKey "${gk}" spans typography slots {${[...slots].join(', ')}}: ${vars.join(', ')}`,
          );
        }
      }
      expect(violations, violations.join('\n')).toEqual([]);
    });
  }
});

// Companion invariant: a typography slot's COLOR must share a link group with
// exactly the same peers as its FONT-SHAPE props.
//
// `typographySlotOf` above only sees the typography-suffixed variables, so it
// can't catch a phantom sibling hiding in a plain `-text` / `-label` color
// token. Those colors are commonly generated by `buildTypeGroupColorTokens`,
// which infers a groupKey from the last dash — fine when the suffix uniquely
// identifies the slot (Badge's `--badge-<variant>-text` → `text`, one slot
// across variants), but wrong when several independent slots end in the same
// word. SideNavigation's section/item/footer text colors all collapsed to
// groupKey `text` and silently linked three unrelated parts, even though their
// fonts were correctly scoped to `section-text-font-family` etc.
//
// The tell is the disagreement: if two type-group color bases share a color
// groupKey, their `-font-family` companions must share a font groupKey too (and
// vice versa). When the colors merge slots the fonts keep apart, the color is
// the phantom sibling. This compares partitions, so it doesn't fire on the
// legitimate case where a color simply has more state variants than the font
// (Button paints per-state text colors but one font per variant).
describe('editor color/font link-group parity', () => {
  for (const entry of getComponentRegistryEntries()) {
    it(`${entry.id}: typography color link groups match their font link groups`, () => {
      const schema = entry.schema as Array<{ variable: string; groupKey?: string }>;
      const groupKeyOf = new Map(schema.map((t) => [t.variable, t.groupKey]));
      const declared = new Set(schema.map((t) => t.variable));
      // A type-group color base is a color token that has a -font-family companion.
      const bases = schema
        .map((t) => t.variable)
        .filter((v) => declared.has(`${v}-font-family`));

      const violations: string[] = [];
      for (let i = 0; i < bases.length; i++) {
        for (let j = i + 1; j < bases.length; j++) {
          const a = bases[i], b = bases[j];
          const colorA = groupKeyOf.get(a), colorB = groupKeyOf.get(b);
          const fontA = groupKeyOf.get(`${a}-font-family`), fontB = groupKeyOf.get(`${b}-font-family`);
          if (!colorA || !colorB || !fontA || !fontB) continue;
          const colorLinked = colorA === colorB;
          const fontLinked = fontA === fontB;
          if (colorLinked && !fontLinked) {
            violations.push(
              `color groupKey "${colorA}" links ${a} and ${b}, but their fonts are split ` +
                `(${fontA} vs ${fontB}) — the color is a phantom sibling across slots the fonts keep apart.`,
            );
          } else if (!colorLinked && fontLinked) {
            violations.push(
              `font groupKey "${fontA}" links ${a} and ${b}, but their colors are split ` +
                `(${colorA} vs ${colorB}).`,
            );
          }
        }
      }
      expect(violations, violations.join('\n')).toEqual([]);
    });
  }
});
