#!/usr/bin/env node
// Generate src/editor/docs/content.generated.ts from the guide's markdown so
// chapter bodies survive the package boundary. The page used to load them via
// `import.meta.glob('./content/*.md', { query: '?raw' })`, but that's a Vite
// compile-time transform and esbuild's optimizeDeps does NOT expand it inside a
// pre-bundled node_modules dep, so tarball consumers got an empty module and
// every chapter threw "Chapter not found". A plain ES module of string literals
// has no dependency on the bundler. Mirrors tokens.generated.css /
// sync:component-defaults: the .md files stay the authoring source, this is the
// shipped artifact, and `check:docs-content` gates drift.
//
//   node scripts/sync-docs.mjs [--write|--check]
//
// --write (re)generates the file; --check (CI gate) exits 1 on drift; the
// default is a dry run that reports whether the file is current.

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CONTENT = join(ROOT, 'src/editor/docs/content');
const OUT = join(ROOT, 'src/editor/docs/content.generated.ts');

const args = process.argv.slice(2);
const write = args.includes('--write');
const check = args.includes('--check');

const ids = readdirSync(CONTENT)
  .filter((f) => f.endsWith('.md'))
  .map((f) => f.replace(/\.md$/, ''))
  .sort();

const entries = ids
  .map((id) => {
    const md = readFileSync(join(CONTENT, `${id}.md`), 'utf8');
    return `  ${JSON.stringify(id)}: ${JSON.stringify(md)},`;
  })
  .join('\n');

const next =
  `// AUTOGENERATED by scripts/sync-docs.mjs — do not edit by hand.\n` +
  `// Source of truth: src/editor/docs/content/*.md  ·  regenerate: npm run sync:docs\n` +
  `\n` +
  `export const docContent: Record<string, string> = {\n${entries}\n};\n`;

const current = readExisting(OUT);
const drifted = current !== next;

if (write) {
  if (drifted) {
    writeFileSync(OUT, next);
    console.log(`WROTE content.generated.ts (${ids.length} chapters)`);
  } else {
    console.log(`OK — content.generated.ts already current (${ids.length} chapters)`);
  }
} else if (check) {
  if (drifted) {
    console.error(
      `content.generated.ts is out of sync with src/editor/docs/content/*.md.\n` +
        `Run: npm run sync:docs`,
    );
    process.exit(1);
  }
  console.log(`CHECK — content.generated.ts current (${ids.length} chapters)`);
} else {
  console.log(`DRY RUN — ${drifted ? 'DRIFT' : 'clean'} (${ids.length} chapters)`);
}

function readExisting(path) {
  try {
    return readFileSync(path, 'utf8');
  } catch {
    return null;
  }
}
